### ISSUE TITLE
Assigning transactions to cost centers

### ISSUE THREAD

**Issue by kchizi** [ekmungai/eloquent-ifrs#106]
How can a transaction be assigned to a cost center? For example, an invoice to a branch or expense to a department or staff? Later the financial statements can be filtered using this center

**Comment by ekmungai** [comment]
You can use the categories mechanism for that, but only accounts are allowed to have categories so you must ensure to post transactions to those accounts.

Cheers

**Comment by kchizi** [comment]
Thank you, this approach has not worked because the accounts belonging to a category must be of the same type as the category. Trying to figure out how to use the reference field for this case. Would appreciate your guidance.

**Comment by ekmungai** [comment]
Hey @kchizi,

My apologies for the long absence. What I could suggest is setting up a seperate model, say `CostCenter` then extending the Transaction model to have a reference to it. That way you can be filtering transactions using a simple join. 

Cheers
