### ISSUE TITLE
same account type transaction build

### ISSUE THREAD

**Issue by artisanssoft** [ekmungai/eloquent-ifrs#113]
Hi Edward
I have created the transcation base in the account_id/account_type. But some trancation created with same account type
example:-
$clientInvoice = ClientInvoice::create([
'account_id' => $clientAccount->id,

$cashPurchase = CashPurchase::create([
'account_id' => $clientAccount->id,

$clientReceipt = ClientReceipt::create([
'account_id' => $clientAccount->id,

then edward how to create these transactions with line item and post entry in ledgers?

Regards,
Mukesh

**Comment by ekmungai** [comment]
Hi Mukesh,

Different transactions require different account types as the primary account according to the rules of accounting. Please refer to the documentation to determin where the client account goes in each transaction type.

Regards,
Edward
