### ISSUE TITLE
Beginning Reporting Period Transaction Error

### ISSUE THREAD

**Issue by aditiadika** [ekmungai/eloquent-ifrs#114]
Dear @ekmungai,

Please advice, Why can't we do deposit entry on the first day of beginning reporting period? when create journal on beginning period i got error "Transaction date cannot be at the beginning of the first day of the Reporting Period. Use a Balance object instead".

Thanks

**Comment by ekmungai** [comment]
Hi @aditiadika,

It has something to do with how reports are generated. Actually the check does not prohibit transactions on the first day, only transactions at midnight of that day (time 00:00:00). So if you just add some hours for such transactions it should be okay.

Cheers

**Comment by aditiadika** [comment]
Thanks for your reply @ekmungai , solved .
