### ISSUE TITLE
incomeStatement and balanceSheet empty

### ISSUE THREAD

**Issue by EmilioBravo** [ekmungai/eloquent-ifrs#119]
Hi @ekmungai , first, I want to thank you for this amanzing package! I'm trying to implement it in a Laravel app, I've used the examples but the incomeStatement and the balanceSheet shows zero on every field.

What am I doing wrong?

` $incomeStatement = new IncomeStatement('2023-01-01','2023-12-31',$entity);`

`Heliotec
Income Statement
For the Period: Jan 01 2023 to Dec 31 2023

Operating Revenues

Operating Expenses
                        ---------------
Gross Profit                0

Non Operating Revenues
                        ---------------
Total Revenue                0

Non Operating Expenses
                        ---------------
Total Non Operating Expenses    0
                        ---------------
Net Profit                0
                        ===============`

**Comment by ekmungai** [comment]
Hi @EmilioBravo,

Thanks for reaching out. Just so we can narrow down the possible error, what happens when you construct the income statemenet without specifiying the entity?

 `$incomeStatement = new IncomeStatement('2023-01-01','2023-12-31');`
