### ISSUE TITLE
How to start an opening balance like capital

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#14]
I'm not an accountant but I have this question if a company has capital or loans. Entity opening balance

**Comment by ekmungai** [comment]
Both would fall in the Liabilities side of the Balance Sheet. For intance you have $100 cash, of which $50 is capital and $50 is a loan, You'd have a Cash Account with an opening balance of $100 (Debit), A Share Capital Account with a balance of $50 (Credit) and a Loan Account with an opening balance of $50 (Credit )

**Comment by martuico** [comment]
Hi @ekmungai  

Thank you for your response. Do you have a code sample for doing this journal entry?

**Comment by ekmungai** [comment]
Hi @martuico,

Sure

```
use IFRS\Transactions\JournalEntry;

$journalEntry = JournalEntry::create([
    'account_id' => $bankAccount->id,
    'date' => Carbon::now(),,
    'credited' => false,
    'narration' => "Balance Sheet Opening Balances",
]);

$capitalLineItem = LineItem::create([
    'vat_id' => $vat->id,
    'account_id' => $capitalAccount->id,
    'description' => "Capital Opening Balance",
    'amount' => 50,
]);

$loanLineItem = LineItem::create([
    'vat_id' => $vat->id,
    'account_id' => $loanAccount->id,
    'description' => "Loan Opening Balance",
    'amount' => 50,
]);
$journalEntry ->addLineItem($loanLineItem)
->addLineItem($capitalLineItem)
->post();
```

**Comment by martuico** [comment]
I see there's a Journal Entry model thanks!
