### ISSUE TITLE
This is Cash basis or accrual basis system

### ISSUE THREAD

**Issue by b2bexecutives** [ekmungai/eloquent-ifrs#149]
Hi @ekmungai 

Dear this package belongs to which accounting system (Cash basis or accrual basis)

Best regards

**Comment by ekmungai** [comment]
Hi there,

Exellent question. Being IFRS compliant, the package is accrual basis accounting as cash basis is not allowed by the standard. All execpt the cashflow statement of course.

Cheers.

**Comment by b2bexecutives** [comment]
Thanks you @ekmungai;
