### ISSUE TITLE
Reversing cash purchases. 

### ISSUE THREAD

**Issue by ArnoldNicole** [ekmungai/eloquent-ifrs#154]
A Debit Note transaction is used to reverse a purchase made on credit, either in full or partially.

What transaction should be used for reversing cash purchase from suppliers.

**Comment by ekmungai** [comment]
Hi @ArnoldNicole,

As cash purchase reversals constitute an uncommon occurence, they are usually handled via Journal Entry transactions

Cheers,
Edward
