### ISSUE TITLE
Entity 'ABC' has no reporting period defined for the year 2024

### ISSUE THREAD

**Issue by AAUU-Ansari** [ekmungai/eloquent-ifrs#156]
Dear @ekmungai,
First thanks to you for the good account package, I want some help from you which is that I am working on it as the financial year 2023   but now it shows an error  Entity 'abs' has no reporting period defined for the year 2024 but my financial year is 1-july-2023 to 30-june-2024

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari,

Please check and ensure that the `year_start` property of the entity is set to July (7) and not the default January (1).

Cheers
