### ISSUE TITLE
Two users table ?

### ISSUE THREAD

**Issue by iammemon** [ekmungai/eloquent-ifrs#157]
The package creates a new user table with the prefix and suggests using the `ModelTablePrefix` trait in the user model to point `eloquent` to the new table. But what about the existing users and foreign keys?

I can fix it by skipping the `ModelTablePrefix` trait and manually adding the entity_id column in the original user table. But why does it default to this behavior in the first place?

**Comment by ekmungai** [comment]
Hi @iammemon,

That was the original behaviour in a much earlier version of the package, but it was pointed out that someone might want to keep the users from an existing application separate from the new ifrs functionality hence the trait. A simple solution for dealing with existing users/relationships is to add a one to one relationship between the existing users and the ifrs users and then access one or the other from either side.

Cheers,
Edward
