### ISSUE TITLE
The Account Statement's balance and trial balance are different  

### ISSUE THREAD

**Issue by AAUU-Ansari** [ekmungai/eloquent-ifrs#158]
Hi, Dear 
First thank you for the great package. A litter problem now I am facing the trial Balance and the Balance sheet report shows a balance without including the opening balances

it calculates only debit or credit
The Account Statement's balance and trial balance are different  
For example
'ABC Bank' opening balance = $31052
In Trail Balance Report Shows
ABC Bank = $11000

But In Account Statement 
ABC Bank = $42052.77

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari , 

That is indeed a very peculiar issue. Are you sure that the statement and trial balance dates match exactly?

**Comment by AAUU-Ansari** [comment]
Hi @ekmungai 
When I add the closing balances of 2023 to the opening balance of 2024 then the problem gets solved

**Comment by AAUU-Ansari** [comment]
hi @ekmungai 
I am working on this package. All things are working fine but when I close the year 2023 and open the new year 2024 the trail balance & account statement balance do not match.
The trial balance report does not show a Capital balance and the account statement report shows a Capital balance from 2023 to 1-Feb-2024 $134.50283

when I started the year 2023 then I entered the opening balance in (ifrs_balances table) 
is it correct way or not $8.86301

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari ,

You need to create an opening balance equal to the previous years closing balance every time you close an year.

Cheers,
Ed

**Comment by AAUU-Ansari** [comment]
But now trail balance shows account balance correct and accounts statement
show incorrect balance like it add opening balance
Like balance is $100 and the account
 statements report shows it $200

**Comment by AAUU-Ansari** [comment]
Hi @ekmungai 
how to generate an ifrs_closing_transactions entry & please share a code of a complete example of ifrs_closing_transactions entry. may be above #158 issue will be resolved by it

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari,

Statement balances always include the opening balance amount. If the statement has no other transactions the statement and opening balances would be the same. Closing transactions are only meant for recognizing forex differences and would not help at all in this case.

Cheers,
Edward

**Comment by AAUU-Ansari** [comment]
Thanks for your reply,
Dear @Edward Mungai
Can you share me Laravel Blade code for the Account Statement or Trail
Balance maybe I am doing something wrong with it

**Comment by ekmungai** [comment]
Hey @AAUU-Ansari ,

I'm afraid I've not done any front end work on the package and so I cant help.

**Comment by b2bexecutives** [comment]
Hey @ekmungai 
same issue with us the Account Statement show inaccurate balance when we use opening balances of two years

**Comment by AAUU-Ansari** [comment]
Hey @ekmungai,

I hope this message finds you well. Firstly, thank you for this valuable package.

when "currency_id" is passed, the statement returns the sum of (Closed & Open year) opening balances of the account. However, when otherwise correct results are obtained.

$statement = new AccountStatement($request->account_id,null, $request->start_date, $request->end_date);

**Comment by AAUU-Ansari** [comment]
and update the Account Model Line No.350
// $period = ReportingPeriod::getPeriod($year . "-01-01", $entity);
    $period = ReportingPeriod::getPeriod($year ."-". $entity->year_start."-01", $entity);
