### ISSUE TITLE
Compound Entry Error "Total Debit amounts do not match total Credit amounts"

### ISSUE THREAD

**Issue by AAUU-Ansari** [ekmungai/eloquent-ifrs#161]
Hi Dear,
I am facing an issue with the compound entry which is that when we post an entry that has the same account more than 1 time then it shows an unbalanced Transaction Exception

![Capture](https://github.com/ekmungai/eloquent-ifrs/assets/106149988/60ad9390-53d0-4712-b788-81665ab82904)

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari,

I'd never thought of a scenario when you'd need two seperate line items for the same account. I'll take a look at it.

Cheers,
@AAUU-Ansari

**Comment by AAUU-Ansari** [comment]
Thanks to the replay I want to share the scenario of duplicate  line items 

![1](https://github.com/ekmungai/eloquent-ifrs/assets/106149988/1ccef505-07c7-4cb8-9367-11d92ff85bb3)

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari ,

I've implemented and included the requested feature in the latest release.

Cheers,
Edward
