### ISSUE TITLE
Client Receipt LineItem Account must be of type Bank

### ISSUE THREAD

**Issue by AAUU-Ansari** [ekmungai/eloquent-ifrs#167]
Hi Dear
When I create a receipt with income tax it shows the exception 'Client Receipt LineItem Account must be of type Bank'
actually, when we sell products to clients at the time of payment, they deduct 1 percent of the total amount then how to add a receipt entry 
for example, 
sell product 100$
receipts 99$
income tax 1%

**Comment by ekmungai** [comment]
Hi @AAUU-Ansari,

Yes I'm familiar with the transaction you're talking about, its called Witholding Tax. Unfortunately the package is not currently configured to handle this type of tax. as a work around you can record the receipt for $99 then create a journal crediting the client and debiting the appropriate tax account with with $1. Hope this helps.

Cheers
