### ISSUE TITLE
Need Information

### ISSUE THREAD

**Issue by AEK-BKF** [ekmungai/eloquent-ifrs#17]
Hello,
First of all, I'd like to thank you so much for this great package.
Please, I found this section : https://ekmungai.github.io/ifrs-docs/docs/reporting-periods/
Could you explain more (By example) how it works ?

Thanks

**Comment by ekmungai** [comment]
Hi AEK,

This section would mostly have to be set up by an Accountant, as it has to do with the reporting cycle of a business. I will nevertheless attempt to explain with a simple example. In most countries, for the purpose of taxes a business runs for a period of 12 months. This is called the Reporting Period. All reports prepared by the business for taxes, credit etc are always tied to a particluar reporting period. As by the example in the README file, once transactions have been entered and you want to generate reports for the business, a new Reporting Period object is required like so:

``` 
use IFRS\Models\ReportingPeriod;

$period = ReportingPeriod::create([
    'period_count' => 1,
    'year' => 2020,
]);
``` 
Where the period count is simply a convinience for keeping track how many reporting periods/years the company has been using the system and the year is the calendar year that corresponds to the period. The status attribute has to do with accounting conventions that state that once a year has been closed (Audited) no more changes are allowed.

I hope this helps.

Cheers

**Comment by AEK-BKF** [comment]
Thank you so much for quick answer.
