### ISSUE TITLE
Class '\App\User' not found

### ISSUE THREAD

**Issue by AEK-BKF** [ekmungai/eloquent-ifrs#18]
Hi,
I get this error when I configured User Model as you mentioned in docs.
`Class '\App\User' not found`

Laravel : 6.x

**Comment by ekmungai** [comment]
I'd need more details to be able to diagnose the problem. Could you post the entire stack trace?

**Comment by AEK-BKF** [comment]
Thanks for quick reply,
Yes sure, I set up my User Model (in App\User) like in docs :
```
<?php

use IFRS\Traits\IFRSUser;
use IFRS\Interfaces\Recyclable;
...

class User ... implements Recyclable {
  ...
  use IFRSUser;
  ...
}
...
?>
```

**Comment by ekmungai** [comment]
That seems okay, where do you get the error? when you run the tests? Have you also gone through the example on the README?

**Comment by AEK-BKF** [comment]
The errors appears when I implement the User model from Recyclable,
If I remove it, it works fine !

**Comment by ekmungai** [comment]
Huh, thats rather perculiar

**Comment by jonagoldman** [comment]
@AEK-BKF Is your User model set in IFRS config `/config/ifrs.php` and Laravel Auth config `/config/auth.php`?

**Comment by AEK-BKF** [comment]
@jonagoldman 
1. Yes
2. Yes
3. Yes

**Comment by AEK-BKF** [comment]
Okey I fiexd it by:
 -> Adding SoftDeletes to User Model, make migration to add the field.
 -> Adding Recycling Trait also.

The doc needs improvement.

Thanks
