### ISSUE TITLE
description field missing

### ISSUE THREAD

**Issue by AEK-BKF** [ekmungai/eloquent-ifrs#19]
Hello,
After installing the package, the field description in Account Model is missed.

Thanks.

**Comment by jonagoldman** [comment]
Hi, what do you mean by "field missing"? Do you get an exception?

I see the field is created and fillable here:

**Account Migration**
https://github.com/ekmungai/eloquent-ifrs/blob/6758aa98ac9c5705830bc12703e35d87df31d5c0/database/migrations/2020_01_16_215416_create_ifrs_accounts_table.php#L37-L40

**Account Model**
https://github.com/ekmungai/eloquent-ifrs/blob/0d7086b7fb53788347cd3ea561a265247e53566f/src/Models/Account.php#L101-L109

**Comment by AEK-BKF** [comment]
Yes I see them, but when I installed it, I didn't find it in Account Model.

**Comment by jonagoldman** [comment]
Yes, `description` was added to `master` but not released, so it will be fixed once a new version is tagged.
I guess a similar thing happened with `account_id` / `entity_id`, ping @ekmungai.

**Comment by AEK-BKF** [comment]
Thanks for answer, Hope he will release it soon and improve the docs :)

**Comment by ekmungai** [comment]
@jonagoldman I've been making a lot of refinements on the master to make it better usable for generating the more complicated cashflow statement, which is why its taken quite a while. I'm more or less done now and once I've updated the docs I'll be tagging version 3 soon. Thanks a lot for the feedback.

**Comment by jonagoldman** [comment]
@ekmungai Great :rocket:  ! I've being waiting for the right time to start using the package on a project I'm working on.
I will try the new version once released and maybe provide some feedback/help if needed. Thanks!.

**Comment by AEK-BKF** [comment]
@ekmungai Thanks for reply, we're waiting for new release :)
