### ISSUE TITLE
Auth::user()->entity returns Null

### ISSUE THREAD

**Issue by AEK-BKF** [ekmungai/eloquent-ifrs#21]
Hello,
I have issue when I create any record for Account, VAT, ... etc

` auth()->user()->entity` returns null

Laravel version 6.18.40
PHP version 7.4.10

![Screenshot_2020-09-24 🧨 Trying to get property 'id' of non-object](https://user-images.githubusercontent.com/16412739/94130452-589c1f00-fe65-11ea-9814-d33a1131781b.png)

**Comment by ekmungai** [comment]
Like the docs say, every object in the package must be associated with an entity. That means that before creating anything you must first create a entity object and associate it with the current logged in user.

**Comment by AEK-BKF** [comment]
Thanks for reply,
Yes, I've already created the entity, currencies,  vats, ..etc
So, if I create new account like this :

```
$bankAccount = Account::create([
    'name' => "Sales Account",
    'account_type' => Account::BANK,
]);
```
It throws the error, Even if I do like this :

```
$bankAccount = Account::create([
    'name' => "Sales Account",
    'account_type' => Account::BANK,
    'currency_id' => $currency_id,
    'entity_id' => $entity_id,
]);
```

**Comment by ekmungai** [comment]
Verify two things:

1. Is there a logged on user
2. Is the logged on user associated with the entity you created

**Comment by AEK-BKF** [comment]
1- Yes
2- Yes

**Comment by ekmungai** [comment]
Then it must be an evironment issue, not a problem with the package itself. Try creating a new session and starting from scratch.

**Comment by AEK-BKF** [comment]
I'm really sorry, I deleted entity and create new one without assigning it to User.... Oh my Bad ....
Sorry ....
