### ISSUE TITLE
Cash Account vs Bank Account (and general IFRS Standard Accounts)

### ISSUE THREAD

**Issue by jonagoldman** [ekmungai/eloquent-ifrs#22]
I studied basic accounting a long time ago, I remember that in the Assets Accounts there was a **Cash** Account and a **Bank** Account. The Cash account was used for actual money that you have in your hand, for example in a business cash register. The Bank Account was used for all other types of payments.

1) I see this package uses the Bank Account for all cash payments, is that IFRS Standard?
2) Is it possible to have an example of how a discount should be registered using this package? Is a Discount Account needed?
3) I'm not not able to find the IFRS Standard Account Codes list, do you have a link?

I found some related documents in [IFRS Taxonomy Illustrated](https://www.ifrs.org/issued-standards/ifrs-taxonomy/ifrs-taxonomy-illustrated/#lllustrated2020):

- [IFRS Taxonomy 2020 (organised by financial statement)](https://cdn.ifrs.org/-/media/feature/standards/taxonomy/2020/taxonomy-illustrated/taxonomy-en-r-2020-pdf.pdf?la=en)
- [IFRS Taxonomy 2020 (organised by IFRS Standard)](https://cdn.ifrs.org/-/media/feature/standards/taxonomy/2020/taxonomy-illustrated/taxonomy-en-s-2020-pdf.pdf?la=en)
- [IFRS Taxonomy 2020 (for the IFRS for SMEs Standard](https://cdn.ifrs.org/-/media/feature/standards/taxonomy/2020/taxonomy-illustrated/taxonmy-en-sme-r-2020.pdf?la=en)

I also found [this .zip file](https://cdn.ifrs.org/-/media/feature/standards/taxonomy/2020/ifrst_2020-03-16.zip?la=en) with various files in XML format.

Thanks.

**Comment by ekmungai** [comment]
Hi Jona, let me try and answer each of your questions in turn.

1 & 3. As opposed to the US GAAP, The IFRS standard does not, as far as I know have a recommended account code list. It only suggests categorization for each section of the financial reports. For instance, in the Balance Sheet, The standard talks of Cash and Cash Equivalents which includes both Cash and Bank accounts. This is why I labeled the category Bank just for clarity's sake. If one wanted to have distinct accounts for bank and cash, one possible way to accomplish that is to create seperate Bank categories for them.

2. To handle a discount, yes one would need an expense account for discounts allowed. That way when you record a cash sale worth $100 with a 10% discount you can do the following entries:

Credit        Operating Revenue Account                        $100
       Debit          Bank Account                                                     $90
       Debit          Discounts Allowed Account                                $10

I hope this clarifies matters.

Cheers.

**Comment by jonagoldman** [comment]
Thanks for the fast reply.

I guess thats why I could't find account codes :)

I saw you set some account codes constants like  1000, 1500, 2000 and also found some articles numbering accounts like an ordered list: 1, 1.1, 1.1.1, ...

But I understand that the codes are just for internal use.

Regarding discounts (and other potential operations), it will be very helpful once you have the time, to add a few more examples to the docs. Altough it is clear that the package is meant to be used together with an accountant, it can clarify some things for the developer until they get the chance to actually talk with an accountant.

Thanks.

**Comment by ekmungai** [comment]
Hi Jona, 

I'm almost done with the changes I've been making to the master in preparation for the next release. I'll work on adding a comprehensive example in the next version of the docs. Regarding the account codes, I specifically set them up as constants in the config file so that the developer can configure them into whatever their accounting team works with.

Cheers.

**Comment by jonagoldman** [comment]
Oh great! So I will wait for the release then.
Thanks.

**Comment by AEK-BKF** [comment]
Can't wait for next release ! I hope it'll be soon ^^'
