### ISSUE TITLE
Question about next release

### ISSUE THREAD

**Issue by AEK-BKF** [ekmungai/eloquent-ifrs#23]
Hello @ekmungai,
According to this : https://github.com/ekmungai/eloquent-ifrs/issues/22#issuecomment-701391469;
Just a question please, will the next release have a big changes and need deep refactoring on the old one or just an upgrade and everything goes fine ?
And also, if I can ask you, will this release be done soon? if you can give us an expected date. (Sorry for this question but I have a project and I really need it)

Thanks

**Comment by ekmungai** [comment]
Hi  BKF,

I'm really sorry I wasn't able to deliver the next release at the timetable I mentioned, some circumstances beyong my control came into play and I had no choice. That being said, I've more or less finished writing the code for the new version, all that is remaining is the documentation. Regarding the upgrade, while most of the functionality of the current version will not be too much affected obviating the need for too much refactoring, there are model changes that affect migrations which might cause compatibility issues. While updating the documentation I'll make sure to include an upgrade guide with all the sections that require special attention. As far as the actual release dat is concerned, as mentioned earlier the main thing remaining is the documentation. I would therefore conservatively put the release date as sometime within November.

With many thanks for your support and feedback,
Edward

**Comment by AEK-BKF** [comment]
Thank you so much for clarification.

**Comment by ekmungai** [comment]
@AEK-BKF @jonagoldman I've just finished setting up the documentation for version 3 which I'm just about to release. I'm sorry I took so long, but I would really appreciate if you went through it (especially the upgrade guide and example sections) and let me know what you think before I do the release. 

Cheers

**Comment by jonagoldman** [comment]
@ekmungai let me know when the pre release or dev branch is available so I can test it out.

**Comment by ekmungai** [comment]
@jonagoldman pre realease is published!

**Comment by jonagoldman** [comment]
Great! Will try it out in the next few days and get back to you. Thanks!

**Comment by jonagoldman** [comment]
Hi, I can't test it right now but I will get back to it in a month or so.

**Comment by ekmungai** [comment]
Hi Jona, no worries. Happy Holidays
