### ISSUE TITLE
Laravel 8 & PHP 8 Not Supported

### ISSUE THREAD

**Issue by eorenstein1** [ekmungai/eloquent-ifrs#26]
Installation on a fresh Laravel 8 project fails.

`ekmungai/eloquent-ifrs dev-master requires illuminate/database ^6.0|^7.0 -> found illuminate/database[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.`

Also, PHP 8 is not supported.

**Comment by ekmungai** [comment]
Hi eoreinstein,

The package is primarily targeted towards Laravel 6 and 7 and definitely php 7. I will think about upgrading it to Laravel and php 8 but that's not a priority at the moment.

Cheers
