### ISSUE TITLE
How to add opening balance on the account

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#27]
<img width="890" alt="Screen Shot 2021-02-10 at 3 29 57 AM" src="https://user-images.githubusercontent.com/2949921/107417155-412dac00-6b50-11eb-8496-f314fcd43d5f.png">

**Comment by ekmungai** [comment]
Hi Mar,

You can use the Balance and as of (as Transaction Date) fields to create a Balance object as described [here](https://ekmungai.github.io/ifrs-docs/v3docs/balances/).

Cheers

**Comment by martuico** [comment]
Hi @ekmungai  

Thank you for your response really appreciate it. Do you have a sample code for balances?  I'm a bit confused there are attributes that need to created like transaction_type, balance_type, and etc. since I would need to have credit and debit at the same time.

Thanks,
Mar

**Comment by ekmungai** [comment]
Hi Mar,

Sorry I so long to reply. I don't example code at the moment, but a balance can only have a debit or a credit balance_type, not both since they would cancel each other.

Cheers,
