### ISSUE TITLE
Balance sheet report has string 1111111111

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#38]
Hi @ekmungai 

When generating balance sheet it gives me 11111 in front.

`public function balanceSheet(Request $request)
    {
     
        $balanceSheet = new BalanceSheet();
        $balanceSheet->attributes();
        $balanceSheet->getSections();
        return response()->json($balanceSheet, 200);
    }`
<img width="793" alt="Screen Shot 2021-03-30 at 4 31 13 AM" src="https://user-images.githubusercontent.com/2949921/112896467-03d9a980-9111-11eb-81fd-11ec8e165116.png">

**Comment by ekmungai** [comment]
Hi Mar,

That is indeed strange. Do they appear when you dd($balanceSheet)?

**Comment by martuico** [comment]
Hi @ekmungai 

Yes, it does.

<img width="938" alt="Screen Shot 2021-03-31 at 2 20 53 AM" src="https://user-images.githubusercontent.com/2949921/113037243-c552f600-91c7-11eb-97c3-b7e798b10c5b.png">

**Comment by ekmungai** [comment]
Hmm. Which version are you on?
