### ISSUE TITLE
laravel 8 not support

### ISSUE THREAD

**Issue by devlover-xyz** [ekmungai/eloquent-ifrs#42]
hello, 
in latest release v.3.1.4 not yet support laravel 8.
![image](https://user-images.githubusercontent.com/61451075/115339986-1145f900-a1d0-11eb-8593-0278d31847c3.png)

**Comment by ekmungai** [comment]
Hi @devlover-xyz, my apologies, I'd not released the compatible version yet, now I have. Please require v4.0.0
