### ISSUE TITLE
Unable to install in Lumen version 8

### ISSUE THREAD

**Issue by Wraptechologies** [ekmungai/eloquent-ifrs#43]

**Comment by ekmungai** [comment]
Hi @Wraptechologies my apologies, I'd not released the compatible version yet, now I have. Please require v4.0.0

**Comment by Wraptechologies** [comment]
HI ekmungai thanks for the quick reply and build, I am using Lumen Rest API version 8, is this package could be suitable for it? or do I need something extra for it for LUMEN ? need help i am new in Lumen

**Comment by ekmungai** [comment]
Hi @Wraptechologies since Lumen uses eloquent, there should not be anything extra required

Cheers,
Edward

**Comment by Wraptechologies** [comment]
please try your self you got an idea, after installation and  php artisan migrate gives "Nothing to migrate."

**Comment by ekmungai** [comment]
@Wraptechologies Hmm, I hadnt actually tried to install it on lumen, I'll give it a try and see.

Thanks for the feedback, 
Edward

**Comment by Wraptechologies** [comment]
Thanks ekmungai

**Comment by Wraptechologies** [comment]
Hi ekmungai 
please help regarding lumen framework version#8.0 as you know lumen not support vender:publish command 

Thanks and Regards
Faisal Sharif

**Comment by ekmungai** [comment]
Hi Faisal,

As you pointed out, there are some functionalities that Lumen does not have that I had just assumed would be there. As such, I need some time to prepare workarounds for them to enable installation of the package.

Thanks again for pointing this out.
Edward

**Comment by Wraptechologies** [comment]
Thanks, Edward

Patience is bitter , but its fruit is sweet :)

Thank you for reply 
Faisal Sharif

**Comment by ekmungai** [comment]
Hi Faisal,

I've made some changes to the code and also updated the readme with instructions on how to install the package when using lumen. Please upgrade to version v4.0.1 and follow the instructions and let me know if you succeed.

Cheers,
Edward

**Comment by Wraptechologies** [comment]
Hi Edward
Thank you for the update 

Installation now successfully, all migration done completed 

I have tested your SaleCycle 
https://ekmungai.github.io/ifrs-docs/v3docs/sales-cycle/

but at the end, it gives the following error

Call to a member function post() on null (500 Internal Server Error)
