### ISSUE TITLE
BadMethodCallException 

### ISSUE THREAD

**Issue by ArnoldNicole** [ekmungai/eloquent-ifrs#44]
implementing  the following traits 
```
use IFRS\Traits\IFRSUser;

use IFRS\Traits\Recycling;

use IFRS\Interfaces\Recyclable;

class User  extends Authenticatable implements Recyclable {
  ...
  use IFRSUser;
  use Recycling;
  ...
}
```
`Call to undefined method App\Models\User::restoring()`

in laravel version 8, also tried `php artisan migrate:fresh`

**Comment by ekmungai** [comment]
Hi Arnold, 

Thanks for reaching out, try upgrading to version 4.0.0 and try again

Cheers,
Edward

**Comment by shahonseven** [comment]
I solved this by enabling soft deletes in my user model.

**Comment by Wraptechologies** [comment]
> I solved this by enabling soft deletes in my user model.

Thanks Shahonseven
