### ISSUE TITLE
Auth::user()->entity->id

### ISSUE THREAD

**Issue by gauravatwork01** [ekmungai/eloquent-ifrs#48]
for the line  $model->entity_id = Auth::user()->entity->id; in src/Traits/Segregating.php i am getting an error-> Trying to get property 'id' of non-object, seems like Auth::user()->entity is supposed to be an object which is not happening, have included the traits IFRSUser and Recycling in the User model and have also implemented the Recyclable interface in User model.

**Comment by gauravatwork01** [comment]
also i am using 3.1.4 version

**Comment by ekmungai** [comment]
Hi @gauravatwork01,

That can only mean that the user has no associated entity for it. Please make sure you set the current logged in user's entity_id to an existing entity before attempting to create any more models.

Cheers,
Edward

**Comment by rutujathakre09** [comment]
Hi @gauravatwork01 ,have you found solution?

**Comment by hicka** [comment]
@gauravatwork01  and @rutujathakre09 , follow these steps and see if you still get the error.

$user = Auth::user();

$entity = Entity::create([
    "name" => "Example Company",
]);

//Entities require a reporting currency
$currency = Currency::create([
    "name" => "Euro",
    "currency_code" => "EUR"
]);

// Set the currency as the Entity's Reporting Currency 
$entity->currency_id = $currency->id;
$entity->save();

$user->entity_id = $entity->id;  // sets the users entity to the created entity
$user->save():

**Comment by abanghendri** [comment]
Hi, it's 2021 and I'm still having the same issue when inserting VAT according to the readme.MD example:

this is my complete code:
`$entity = Entity::create([
            "name" => "Hendri Corp",
        ]);

        $id = Auth::user()->id;
        $user = User::find($id);
        $user->entity()->associate($entity);
        $user->save();
        //Entities require a reporting currency
        $currency = Currency::create([
            "name" => "Rupiah",
            "currency_code" => "IDR",
            "entity_id"     => $entity->id
        ]);

        // Set the currency as the Entity's Reporting Currency 
        $entity->currency_id = $currency->id;
        $entity->save();

        $account_type = config('ifrs')['accounts'];

        foreach($account_type as $key => $type){
            Category::create([
                'name' => $type,
                'category_type' => $key,
                'entity_id' => $entity->id
            ]);
        }
        // Configure VAT

        $bankAccount = Account::create([
            'name' => "Bank Account",
            'account_type' => Account::BANK,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $revenueAccount = Account::create([
            'name' => "Sales Account",
            'account_type' => Account::OPERATING_REVENUE,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $clientAccount = Account::create([
            'name' => "Example Client Account",
            'account_type' => Account::RECEIVABLE,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $supplierAccount = Account::create([
            'name' => "Example Supplier Account",
            'account_type' => Account::PAYABLE,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $opexAccount = Account::create([
            'name' => "Operations Expense Account",
            'account_type' => Account::OPERATING_EXPENSE,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $assetAccount = Account::create([
            'name' => "Office Equipment Account",
            'account_type' => Account::NON_CURRENT_ASSET,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $salesVatAccount = Account::create([
            'name' => "Sales VAT Account",
            'account_type' => Account::CONTROL,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        $purchasesVatAccount = Account::create([
            'name' => "Input VAT Account",
            'account_type' => Account::CONTROL,
            'category_id' => null,
            'currency_id'   => $currency->id,
            'entity_id' => $entity->id
        ]);

        // dd($purchasesVatAccount->id);
        // dd($salesVatAccount->id);
        $outputVat = Vat::create([
            'name'  => 'Standard Output Vat',
            'code'  => 'O',
            'rate'  => 20,
            'account_id' => $salesVatAccount->id,
            'entity_id' => $entity->id
        ]);

        $inputVat = Vat::create([
            'name'  =>"Standard Input Vat",
            'code'  =>"I",
            'rate'  =>10,
            'account_id' => $purchasesVatAccount->id,
            'entity_id' => $entity->id
        ]);

        $zeroVat = Vat::create([
            'name'  =>"Zero Vat",
            'code'  =>"Z",
            'rate'  => 0,
            'account_id' => $purchasesVatAccount->id,
            'entity_id' => $entity->id
        ]);`

And the Vat:: section always get this error
`ErrorException
Trying to get property 'id' of non-object `

The loggedin user is already associated with entity, so what can I do for this error?
