### ISSUE TITLE
Error when updating $entity->currency_id field

### ISSUE THREAD

**Issue by morrisonmburu** [ekmungai/eloquent-ifrs#50]
I get an error when running the script below
![Screenshot 2021-06-04 132741](https://user-images.githubusercontent.com/35775730/120789285-1c63a700-c53a-11eb-9304-c08d7a50074c.jpg)
.....
the error
![Screenshot 2021-06-04 132710](https://user-images.githubusercontent.com/35775730/120789406-3ef5c000-c53a-11eb-9110-36a0b2e84ca2.jpg)

Kindly @ekmungai advice on how to fix it

**Comment by ekmungai** [comment]
Hi Morris,

The error was caused by a typo in the example code. the line `$entity->currency_id = $currency` should actually read `$entity->currency_id = $currency->id`. I've updated the readme to reflect the change, thanks for catching it.

Cheers,
Edward
