### ISSUE TITLE
Incorporating Subsidiary Accounts as part of the package.

### ISSUE THREAD

**Issue by DonAmbrose** [ekmungai/eloquent-ifrs#52]
Firstly, I would like to thank you @ekmungai for developing this rather useful package. Am currently exploring its key features and am quite impressed by your work. This package is very interesting especially when it comes to summarizing financial information about a firm.

From a transactions and books of prime entry perspective,  I would like to know how the package works. Specifically, I would like to know if this package supports subsidiary accounts (not part of  general ledger accounts)that would help to track individual transactions which can be reconciled to the general ledger accounts. For instance, if a client makes several credit purchases from our firm and later makes payments to settle these earlier purchases. Can we be able to generate a separate account in form of client statement that shows a history of the transactions for the specific client. 

Thank you once again for  your continued effort of helping budding developers.

**Comment by ekmungai** [comment]
Hi @DonAmbrose,

Thanks for your kind words. Please take a look at the documentation around the AccountStatement object as I believe it fullfils the example you mentioned above.

Cheers,
Edward

**Comment by DonAmbrose** [comment]
Thank you sir...let me try check it out
