### ISSUE TITLE
Relating Custom Models to accounting  example Track products with SKU or Suppliers by id 

### ISSUE THREAD

**Issue by elbakly** [ekmungai/eloquent-ifrs#59]
Hi Edward,
Awesome job and great effort,

I have a question on what is the purpose of entities here? and if it is used for custom Model relations , then can you provide example of how to relate to a specific record in supplier for example in Credit Purchase transaction.

If you don't have an answer , then let me propose a solution and we can work it together

**Comment by ekmungai** [comment]
Hi @elbakly,

I'm not sure I quite follow your question, but an entity is intended to represent the business unit/company whose accounts are being managed by the package. I'm afraid I'm not familiar with the SKU acronym, but as far as tracking products is concerned I intentionally left it out so as to give developers the maximum flexibility on how to account for them. For an example of the supplier transaction, you can take a look at the Examples section of the documentation [here](https://ekmungai.github.io/ifrs-docs/v3docs/sales-cycle/).

Cheers.

**Comment by elbakly** [comment]
Hi @ekmungai 
Thank you for the prompt reply,  You have replied both questions, SKU is Stock Keeping Unit  [details](https://en.wikipedia.org/wiki/Stock_keeping_unit).
