### ISSUE TITLE
Invoice Assignment not working

### ISSUE THREAD

**Issue by FahadRafique229** [ekmungai/eloquent-ifrs#70]
Call to undefined method IFRS\Models\Transaction::getClearedType()
During Assignment I am facing this issue please guide me on how to create an invoice Assignment?
Please check this code:
$assignment = Assignment::create([
    'transaction_id' => $clientReceipt->id,
    'cleared_id' => $clientInvoice->id,
    'cleared_type'=> $clientInvoice->getClearedType(),
    'amount' => 50,
]);

**Comment by hicka** [comment]
Try

'cleared_type'=> $clientInvoice->clearedType
