### ISSUE TITLE
Considering to add compound/combined journal entry feature

### ISSUE THREAD

**Issue by abanghendri** [ekmungai/eloquent-ifrs#72]
> compound entry is a more efficient form of accountancy, which enhances the productivity of the accountant and leads to a better accounting presentation.
> wallstreetmojo.com

I know there are 3 compound JE
-  multiple Debits : Credit
- Debit : multiple Credits
- Multiple Debits : multiple Credits

Third case is rarely used, but some still need it to better accounting presentation.

So please vote for this if you need this feature to.

**Comment by ekmungai** [comment]
Hi @abanghendri,

The first two scenarios, are already covered by the package, they are controlled by the `$journalEntry->credited` attribute i.e. if true, the main account is on the credit side and all the line item accounts are debited, when false the main account and all the line item accounts are credited. I'll need to spend some time to think about how to implement that third scenario.

Cheers

**Comment by ekmungai** [comment]
Hi @abanghendri.

i'm happy to let you know that I've added support for compound journals to the latest release of the package. To see it in action, please visit the examples section of the documentation.

Cheers

**Comment by abanghendri** [comment]
Thanks @ekmungai , you're awesome
