### ISSUE TITLE
Balance sheet code is not working

### ISSUE THREAD

**Issue by FahadRafique229** [ekmungai/eloquent-ifrs#74]
I am using the below code:
$balanceSheet = new BalanceSheet("2021-12-31");
$balanceSheet->getSections();
dd($balanceSheet->toString());
but its not working. i am getting following error
Maximum execution time of 60 seconds exceeded

**Comment by ekmungai** [comment]
Hi @FahadRafique229,

That error is caused by your php settings, not the package and can happen when you have many records that you are preparing the report for. You can increase the execution time by changing the `max_execution_time` variable in your php.ini.

Cheers
