### ISSUE TITLE
Impact of purchases on inventory in Char of Account

### ISSUE THREAD

**Issue by ovaislak** [ekmungai/eloquent-ifrs#76]
Hi,

I am using this package for a company that is involve in trading of goods.

We were following the documentation to record purchases. While recording a purchase I can see that the tutorial credited the Operational expense account and debited the supplier account. There is no impact on inventory account in chart of accounts. 

Can you please guide my in this case how to properly record the sale and purchase so that I can later see the value of in stock goods.

**Comment by ekmungai** [comment]
Hi @ovaislak,

Thanks for reaching out. To use inventory accounts, there has to be a three-step process. First, you have to record the inventory purchase using the CashPurchase or SupplierBill transactions, putting the inventory account as the account in the line item. This will Credit the Bank/Supplier and Debit the Inventory account. Second, when you make a sale using the CashSale or ClientInvoice, this will Credit the Operating Income account in the line item and debit the Customer/Bank. The final step is to expense the sold goods by transferring the amount from the Inventory account to an Operating Expense account using a JournalEntry. The main account of the JE should be the Inventory account and the line item account should be Operating Expense. This will Credit the Inventory and Debit the Expense.

Hope this helps,
Edward
