### ISSUE TITLE
Remove entity_id from currency table?

### ISSUE THREAD

**Issue by eorenstein1** [ekmungai/eloquent-ifrs#89]
Why does the currency table have an entity_id? Can we remove that to be able to use the same currency for multiple entities?

**Comment by ekmungai** [comment]
The idea behind that is that each entity should be completely independent of the others. Under that assumption, having currencies not created by users of another does not seem like a good idea.

Cheers

**Comment by mauricemojito** [comment]
Little question, what would be the use case here? Because currencies don't change much? Maybe use a link table if we want multi currencies? It's just a question :)

**Comment by ekmungai** [comment]
Hi @mauricemojito,

The original idea was to design the database in such a way that it could handle single database multitenant applications as well as a multidatabase case. With each entity having its own currency records transisioning between the two modes is made easy ;)

**Comment by mauricemojito** [comment]
@ekmungai Thank you!
