### ISSUE TITLE
EntityScope bug

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#91]
Hi, I keep having this issue.

![Screen Shot 2021-09-10 at 3 15 12 PM](https://user-images.githubusercontent.com/2949921/132814984-8277280a-7552-480d-8337-156eed836fe4.png)

**Comment by ekmungai** [comment]
Hi @martuico,

That error indicates that there is no logged in user. I'll add an exception so the reason is clearer.#

Cheers.

**Comment by martuico** [comment]
I force entity_id in Vat to create the error comes from entity id. Also Vat class has error when doing eloquent function like Vat::whereCode()->first() it shoes same error

**Comment by martuico** [comment]
Also when saving transaction
![Screen Shot 2021-09-10 at 10 28 54 PM](https://user-images.githubusercontent.com/2949921/132869737-399bf2fa-fda5-47f7-b065-6d693e8b3896.png)

`$transaction = ($request->get('transaction_type') === 'ES' || $request->get('transaction_type') === 'PO') ?
            null :
            Transaction::getType($request->get('transaction_type'));

        $headerClass = ($transaction) ? "IFRS\Transactions\\" . \str_replace(' ', '', $transaction) : '';
        // return response()->json($headerClass);
        //Create Trasasction
        if (class_exists($headerClass)) {
            $transaction = new $headerClass([
                "account_id" => $request->get('account_id'),
                "transaction_date" => Carbon::now(),
                "narration" => $request->get('narration'),
            ]);
        }
        $lineItems = [];
        foreach ($request->get('line_items') as $item) {
            $lineItem = [
                "amount" => $item['amount'],
                "vat_id" => $item['vat_id'],
                "account_id" => $item['account_id'],
                "narration" => $item['description'],
                "quantity" => $item['quantity']
            ];

            if (class_exists($headerClass) && $transaction) {
                $accLineitem = new LineItem($lineItem);
                $accLineitem->save();
                $accLineitem->attributes();
            }
            // $lineItem = LineItem::create();
            $newLineRow = LineItem::with('vat')->whereId($accLineitem->id)->first();
            $transaction->addLineItem($newLineRow);
            $lineItems[] = $accLineitem;
        }
        Log::info($transaction);
        if (class_exists($headerClass) && $transaction) {
            $transaction->post();
        }
`

**Comment by martuico** [comment]
Found the issue its on my end there's missing data
