### ISSUE TITLE
How to close reporting period

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#95]
How to close reporting period and able to brought forward.

**Comment by ekmungai** [comment]
Hi @martuico,

To close a reporting period, assuming there are no forex transactions, you can either directly change the status of the period to `ReportingPeriod::CLOSED` or use the intermediate `ReportingPeriod::ADJUSTING` to allow journal entries for making audit adjustments before closing the year. Bringing forward the balances to a new year involves creating `Balance` objects for each account that has an outstanding balance by the end of the year.

Cheers,
Edward
