### ISSUE TITLE
bug on running php artisan route:list

### ISSUE THREAD

**Issue by martuico** [ekmungai/eloquent-ifrs#97]
![Screen Shot 2021-10-26 at 10 40 04 AM](https://user-images.githubusercontent.com/2949921/138799759-e791751b-b1a7-48d3-8d85-8c13af3fd082.png)

**Comment by ekmungai** [comment]
Hi @martuico,

The package relies heavily on the laravel's session management system, so artisan commands that are run offline might not work. I havent tested any of them as of yet. What version are you using?

Regards,
Edward
